spring.application.name=gateway
# Netty 서버 포트
gateway.port=8003
api.server.url=http://ex-api-server.com

management.endpoints.web.exposure.include=health,info,metrics
management.endpoint.health.show-details=always