apiVersion: v1
kind: Service
metadata:
  name: massflux-gateway-svc
spec:
  selector:
    app: massflux-gateway
  type: NodePort
  ports:
    - name: netty-tcp
      port: 8003
      targetPort: 8003
      nodePort: 30003
    - name: rest-api
      port: 8080
      targetPort: 8080
      nodePort: 30080